---
repo-name: peripherals-iwise
categories:
- Service Management
- Ticketing
display-name: iWise
manufacture: iWise
product: iWise
description: iWise is an IT Service Management solution based on the ITIL framework. This category includes a collection of handlers useful for interacting with the InfraWise iWise application suite.
