{
  'info' => {
    'endpoint_address' => '',
    'endpoint_port' => '',
    'authentication_username' => '',
    'authentication_password' => '',
    'authentication_transaction_server' => '',
    'authentication_server_port' => '',
    'authentication_account' => '',
    'authentication_session' => '',
    'authentication_group' => ''
  },
  'parameters' => {
    'description' => 'This incident was generated by the iwise_incident_create_v1 handler.'
  }
}